package org.bread_experts_group.rsgauges.util

enum class RsConfigFlags {
	// RsBlock
	RSBLOCK_CONFIG_SOLID,
	RSBLOCK_CONFIG_CUTOUT,
	RSBLOCK_CONFIG_CUTOUT_MIPPED,
	RSBLOCK_CONFIG_TRANSLUCENT,
	RSBLOCK_NOT_WATERLOGGABLE,
	// RsDirectedBlock
	RSBLOCK_CONFIG_WALLMOUNT,
	RSBLOCK_CONFIG_LATERAL,
	RSBLOCK_CONFIG_FULLCUBE,
	RSBLOCK_CONFIG_OPPOSITE_PLACEMENT,
	// SwitchBlock
	// -- Entity stored changeable state data
	SWITCH_DATA_POWERED_POWER_MASK,
	SWITCH_DATA_RESERVED_MASK,
	SWITCH_DATA_INVERTED,
	SWITCH_DATA_WEAK,
	SWITCH_DATA_NOOUTPUT,
	// -- Full block multi-side output control
	SWITCH_DATA_SIDE_ENABLED_BOTTOM,
	SWITCH_DATA_SIDE_ENABLED_TOP,
	SWITCH_DATA_SIDE_ENABLED_FRONT,
	SWITCH_DATA_SIDE_ENABLED_BACK,
	SWITCH_DATA_SIDE_ENABLED_LEFT,
	SWITCH_DATA_SIDE_ENABLED_RIGHT,
	SWITCH_DATA_SIDE_ENABLED_ALL,
	SWITCH_DATA_SIDE_ENABLED_MASK, /* points to SWITCH_DATA_SIDE_ENABLED_ALL */
	SWITCH_DATA_SIDE_ENABLED_SHIFT,
	SWITCH_DATA_ENTITY_DEFAULTS_MASK,
	// -- Constant construction time switch config
	SWITCH_CONFIG_INVERTABLE,
	SWITCH_CONFIG_WEAKABLE,
	SWITCH_CONFIG_PULSETIME_CONFIGURABLE,
	SWITCH_CONFIG_TOUCH_CONFIGURABLE,
	SWITCH_CONFIG_PULSE_EXTENDABLE,
	SWITCH_CONFIG_LCLICK_RESETTABLE,
	SWITCH_CONFIG_BISTABLE,
	SWITCH_CONFIG_PULSE,
	SWITCH_CONFIG_CONTACT,
	SWITCH_CONFIG_TIMER_DAYTIME,
	SWITCH_CONFIG_TIMER_INTERVAL,
	SWITCH_CONFIG_SENSOR_VOLUME,
	SWITCH_CONFIG_SENSOR_LINEAR,
	SWITCH_CONFIG_SENSOR_LIGHT,
	SWITCH_CONFIG_SENSOR_RAIN,
	SWITCH_CONFIG_SENSOR_LIGHTNING,
	SWITCH_CONFIG_SENSOR_BLOCKDETECT,
	SWITCH_CONFIG_SENSOR_TIME, /* points to SWITCH_CONFIG_TIMER_INTERVAL */
	SWITCH_CONFIG_SENSOR_DETECTOR, /* combination of SWITCH_CONFIG_SENSOR_VOLUME and SWITCH_CONFIG_SENSOR_LINEAR */
	SWITCH_CONFIG_SENSOR_ENVIRONMENTAL, /* combination of SWITCH_CONFIG_SENSOR_LIGHT, SWITCH_CONFIG_TIMER_DAYTIME, SWITCH_CONFIG_SENSOR_RAIN and SWITCH_CONFIG_SENSOR_LIGHTNING */
	SWITCH_CONFIG_AUTOMATIC, /* combination of SWITCH_CONFIG_SENSOR_TIME, SWITCH_CONFIG_SENSOR_DETECTOR, SWITCH_CONFIG_SENSOR_ENVIRONMENTAL, SWITCH_CONFIG_SENSOR_BLOCKDETECT */
	SWITCH_CONFIG_PROJECTILE_SENSE_ON,
	SWITCH_CONFIG_PROJECTILE_SENSE_OFF,
	SWITCH_CONFIG_PROJECTILE_SENSE, /* combination of SWITCH_CONFIG_PROJECTILE_SENSE_ON and SWITCH_CONFIG_PROJECTILE_SENSE_OFF */
	SWITCH_CONFIG_SHOCK_SENSITIVE,
	SWITCH_CONFIG_HIGH_SENSITIVE,
	SWITCH_CONFIG_TRANSLUCENT, /* points to RSBLOCK_CONFIG_TRANSLUCENT */
	SWITCH_CONFIG_NOT_PASSABLE,
	SWITCH_CONFIG_SIDES_CONFIGURABLE,
	SWITCH_CONFIG_LINK_SOURCE_SUPPORT,
	SWITCH_CONFIG_LINK_TARGET_SUPPORT,
	SWITCH_CONFIG_LINK_SENDER,
	SWITCH_CONFIG_WALLMOUNT, /* points to RSBLOCK_CONFIG_WALLMOUNT */
	SWITCH_CONFIG_LATERAL, /* points to RSBLOCK_CONFIG_LATERAL */
	SWITCH_CONFIG_LATERAL_WALLMOUNT, /* combination of SWITCH_CONFIG_WALLMOUNT and SWITCH_CONFIG_LATERAL */
	// Entity stored changable state value data
	SWITCH_DATA_SVD_ACTIVE_TIME_MASK
}